# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/go-diodes"

[[constraint]]
  name = "github.com/fukata/golang-stats-api-handler"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "~1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "~1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/shinji62/logrus-syslog-ng"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "~2.1.11"

[[constraint]]
  branch = "master"
  name = "github.com/stvp/go-udp-testing"